// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElRow: typeof import('element-plus/es/el-row')['default']
  }
}

export { }
